"""SRKI acceptance test cases for regression checks."""
from __future__ import annotations

ACCEPTANCE_CASES: list[dict] = [
    {
        "id": "greeting_hello",
        "message": "Hello..",
        "session_id": "acc-greeting",
        "expect_intent": "general_greeting",
        "expect_clarification": False,
        "reply_contains_any": ["SRKI", "Computer Science", "courses"],
        "expect_source_prefix": "greeting",
    },
    {
        "id": "disambiguation_cs",
        "message": "what is about CS ?",
        "session_id": "acc-cs-1",
        "expect_intent": None,
        "expect_clarification": True,
        "reply_contains_any": ["Computer Science", "Communication Skills"],
    },
    {
        "id": "course_cs_overview",
        "message": "Computer Science",
        "session_id": "acc-cs-2",
        "expect_intent": "course_info",
        "expect_clarification": False,
        "reply_contains_any": ["Computer Science Program at SRKI", "PROGRAM OVERVIEW"],
        "expect_source": "curriculum+web",
    },
    {
        "id": "admission_apply",
        "message": "How can I apply for admission for 2026-27?",
        "session_id": "acc-adm",
        "expect_intent": "admission_query",
        "expect_clarification": False,
        "reply_contains_any": ["admission", "Merit", "2026"],
        "expect_source": "web",
        "expect_url_hint": "admission",
    },
    {
        "id": "fees_structure",
        "message": "What is the fee structure at SRKI?",
        "session_id": "acc-fees",
        "expect_intent": "fee_structure",
        "expect_clarification": False,
        "reply_contains_any": ["fee", "Fees", "programme", "M.Sc", "B.Sc", "structure"],
        "expect_source": "web",
        "expect_url_hint": "fees",
    },
    {
        "id": "contact_info",
        "message": "What is the contact phone and email for SRKI?",
        "session_id": "acc-contact",
        "expect_intent": "contact_info",
        "expect_clarification": False,
        "reply_contains_any": ["info@srki.ac.in", "722801849", "Contact"],
        "expect_source": "web",
        "expect_url_hint": "contact",
    },
    {
        "id": "syllabus_mb_sem3",
        "message": "will you give me sem-3 course details of MB ?",
        "session_id": "acc-mb3",
        "expect_intent": "course_info",
        "expect_clarification": False,
        "reply_contains_any": ["Microbiology", "Semester 3", "MSc"],
        "expect_source": "curriculum+web",
    },
    {
        "id": "placement_info",
        "message": "Tell me about placement at SRKI",
        "session_id": "acc-place",
        "expect_intent": "placement_info",
        "expect_clarification": False,
        "reply_contains_any": ["placement", "Placement", "recruit", "career", "722801849"],
        "expect_source_prefix": None,
    },
    {
        "id": "exam_schedule",
        "message": "When is the exam timetable?",
        "session_id": "acc-exam",
        "expect_intent": "exam_schedule",
        "expect_clarification": False,
        "reply_contains_any": ["exam", "Examination", "timetable", "schedule", "paper"],
        "expect_source": "web",
    },
    {
        "id": "infrastructure_library",
        "message": "Does SRKI have a library?",
        "session_id": "acc-lib",
        "expect_intent": "infrastructure_info",
        "expect_clarification": False,
        "reply_contains_any": ["library", "Library", "resource", "campus", "facility"],
        "expect_source": "web",
    },
    {
        "id": "courses_offered",
        "message": "What courses are offered at SRKI?",
        "session_id": "acc-courses",
        "expect_intent": "course_info",
        "expect_clarification": False,
        "reply_contains_any": ["course", "program", "M.Sc", "B.Sc", "Computer Science", "UG-Courses", "offered"],
    },
    {
        "id": "disambiguation_flow",
        "message": "Computer Science",
        "session_id": "acc-cs-flow",
        "expect_intent": "course_info",
        "expect_clarification": False,
        "reply_contains_any": ["Computer Science"],
        "pre_messages": [
            ("acc-cs-flow", "what is about CS ?"),
        ],
    },
    {
        "id": "multi_intent_admission_fees",
        "message": "Tell me about admission process and fees structure",
        "session_id": "acc-multi",
        "expect_intent": "multi_intent",
        "expect_clarification": False,
        "reply_contains_any": ["Admission", "Fees", "topics"],
        "expect_source": "multi-intent",
    },
    {
        "id": "external_vnsgu",
        "message": "What is the admission process for VNSGU university?",
        "session_id": "acc-vnsgu",
        "expect_clarification": False,
        "reply_contains_any": ["VNSGU", "web", "Veer Narmad", "not", "verify"],
        "expect_source": "external_web",
        "network": True,
    },
    {
        "id": "unseen_intent_safe",
        "message": "Who won the cricket world cup blorptastic?",
        "session_id": "acc-unseen",
        "expect_intent": "unknown",
        "expect_clarification": False,
        "reply_contains_any": ["verify", "web", "don't", "SRKI", "assistant"],
        "network": True,
    },
]
